const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path');
const { McpServer } = require('@modelcontextprotocol/sdk/server/mcp.js'); const { StdioServerTransport } = require('@modelcontextprotocol/sdk/server/stdio.js'); const { z } = require('zod');
const core = require('code-glass-core'); const gate = require('code-glass-gate'); const write = require('code-glass-write-path');
const registryPath = path.join(os.homedir(), '.codeglass', 'codeglass.app.config.json');
function resolve(id) { const cfg = JSON.parse(fs.readFileSync(registryPath, 'utf8')); const row = cfg.project_registry.find(x => x.project_id === id); if (!row) throw new Error(`Project not found: ${id}`); return row.manifest_path; }
const server = new McpServer({ name: 'code-glass', version: '1.0.0' });
server.tool('get_status', { project_id: z.string() }, async ({ project_id }) => { const m = await core.loadManifest(resolve(project_id)); return { content: [{ type:'text', text: JSON.stringify({ display_name:m.display_name, stages:m.stages, current_stage_index:m.current_stage_index, overall_completion_pct:m.overall_completion_pct, pending_confirmation:m.pending_confirmation }, null, 2) }] }; });
server.tool('validate_change', { project_id: z.string(), proposed_change: z.object({ description:z.string() }) }, async ({ project_id }) => { const file = resolve(project_id); const m = await core.loadManifest(file); const r = await gate.runBuildTestGate(m.project_path); const next = gate.recordGateResult(m, r); await core.saveManifest(file, next); return { content: [{ type:'text', text: JSON.stringify({ ...r, id: next.gate_log.at(-1).id }) }] }; });
server.tool('record_progress', { project_id:z.string(), target_stage_id:z.string(), target_status:z.string(), summary:z.string(), gate_result_id:z.string().optional() }, async ({ project_id, target_stage_id, target_status, summary, gate_result_id }) => { try { const file=resolve(project_id); const m=await core.loadManifest(file); const next=write.proposeChange(m,{targetStageId:target_stage_id,targetStatus:target_status,summary,requestedBy:'mcp-session',gateResultId:gate_result_id||null}); await core.saveManifest(file,next); return {content:[{type:'text',text:'Change is pending human confirmation and has NOT taken effect yet.'}]}; } catch (e) { return { isError:true, content:[{type:'text',text:`Cannot record progress: ${e.message}. A human must resolve any outstanding confirmation first.`}] }; } });
async function main() { await server.connect(new StdioServerTransport()); } if (require.main === module) main().catch(e => { console.error(e); process.exit(1); });
module.exports = { server, main };
