#!/usr/bin/env node
const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path'); const readline = require('node:readline/promises');
const { stdin, stdout } = require('node:process'); const { Command } = require('commander');
const core = require('code-glass-core'); const gate = require('code-glass-gate'); const write = require('code-glass-write-path');
const configPath = path.join(os.homedir(), '.codeglass', 'codeglass.app.config.json');
function resolveProject(project) { if (project.includes('/') || project.includes('\\')) return project.endsWith('.json') ? project : path.join(project, 'project.codeglass.json'); const cfg = JSON.parse(fs.readFileSync(configPath, 'utf8')); const row = cfg.project_registry.find(x => x.project_id === project); if (!row) throw new Error(`Project not found in registry: ${project}`); return row.manifest_path; }
const projectPath = p => path.dirname(resolveProject(p)); const load = p => core.loadManifest(resolveProject(p)); const save = (p, m) => core.saveManifest(resolveProject(p), m);
const program = new Command(); program.name('codeglass').description('Code Glass project tracker');
program.command('status <project>').action(async p => { const m = await load(p); console.log(`${m.display_name} (${m.project_id})\nCompletion: ${m.overall_completion_pct}%`); m.stages.forEach((s, i) => console.log(`${i === m.current_stage_index ? '→' : ' '} ${s.name} [${s.status}]`)); if (m.pending_confirmation) console.log(`PENDING: ${m.pending_confirmation.summary}`); });
program.command('validate <project>').action(async p => { const m = await load(p); const r = await gate.runBuildTestGate(m.project_path); const next = gate.recordGateResult(m, r); await save(p, next); console.log(`${r.result.toUpperCase()}: ${r.detail}\nGate result id: ${next.gate_log.at(-1).id}`); });
program.command('record <project> <stageId> <status> <summary>').option('--gate-result <id>').action(async (project, stageId, status, summary, opts) => { if (!['not_started','in_progress','complete'].includes(status)) throw new Error('Invalid status'); const m = await load(project); const next = write.proposeChange(m, { targetStageId:stageId, targetStatus:status, summary, requestedBy:'cli-manual', gateResultId:opts.gateResult || null }); await save(project, next); console.log(`PENDING: ${next.pending_confirmation.summary}\nRun codeglass confirm ${project} to commit it.`); });
program.command('confirm <project>').action(async p => { let m = await load(p); if (!m.pending_confirmation) return console.log('No pending confirmation.'); console.log(JSON.stringify(m.pending_confirmation, null, 2)); const rl = readline.createInterface({ input: stdin, output: stdout }); const yes = (await rl.question('Confirm? (y/n) ')).toLowerCase() === 'y'; let next; if (yes) next = write.confirmChange(m); else next = write.rejectChange(m, await rl.question('Reason: ')); rl.close(); await save(p, next); console.log(yes ? 'Change confirmed.' : 'Change rejected.'); });
program.command('snapshot <project> [trigger]').action(async (p, trigger='manual') => { const m = await load(p); const entry = await write.createSnapshot(m.project_path, trigger, path.join(os.homedir(), '.codeglass', 'snapshots', m.project_id)); await save(p, { ...m, snapshots:[...m.snapshots, entry] }); console.log(entry.archive_path); });
program.command('restore <project> <snapshotId>').action(async (project, snapshotId) => { const m = await load(project); const rl = readline.createInterface({ input: stdin, output: stdout }); console.log('WARNING: this will overwrite current project files.'); const yes = await rl.question('Type "yes" to proceed: '); rl.close(); if (yes !== 'yes') return console.log('Restore cancelled.'); await write.restoreSnapshot(snapshotId, m.snapshots, m.project_path, true); console.log('Snapshot restored.'); });
program.parseAsync().catch(e => { console.error(`Error: ${e.message}`); process.exitCode = 1; });
